[package]
name = "pypy-cdn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

anyhow = { version = "1.0.80", features = ["backtrace"] }
async-trait = "0.1.77"
chrono = "0.4.31"
clap = { version = "4.4.18", features = ["env", "derive", "string"] }
dotenvy = "0.15.7"
downcast-rs = "1.2.0"
env_logger = "0.10.1"
futures = "0.3.30"
hex = "0.4.3"
itertools = "0.13.0"
k256 = { version = "0.13.2", features = ["default", "ecdh", "ecdsa", "serde", "ecdsa-core"] }
log = "0.4.20"
rand = "0.8.5"
rmp-serde = "1.1.2"
rust-i18n = "3"
serde = "1.0.197"
serde_derive = "1.0.197"
serde_json = "1.0.114"
serde_yaml = "0.9.32"
thiserror = { version = "1.0.57" }
tokio = { version = "1.35.1", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["full"] }
tokio-util = "0.7.10"
warp = "0.3.6"
warp-range = "2.0.0"
warp-real-ip = "0.2.0"
warp_ratelimit = "1.0.0"
hyper = "0.14.28"
hyper-tls = "0.5.0"
notify = "6.1.1"
uuid = { version = "1.8.0", features = ["v4", "fast-rng"] }
redis = { version = "0.23.3", features = ["tokio-comp", "serde_json", "serde", "json"] }
bb8 = "0.8.1"
bb8-redis = "0.13.1"

rtsp-types = "0.1.1"
